name: CD - Deploy to AWS EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 vai SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            docker pull ${{secrets.DOCKER_USERNAME}}/docker:latest
            docker stop app || true
            docker rm app || true
            docker run -d  \
              --name app \
              -p 8000:8000 \
              ${{secrets.DOCKER_USERNAME}}/docker:latest
